# permissions for end users to edit datatables.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: datatable-editor-role
rules:
- apiGroups:
  - data.fluid.io
  resources:
  - datatables
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - data.fluid.io
  resources:
  - datatables/status
  verbs:
  - get
