apiVersion: data.fluid.io/v1alpha1
kind: AlluxioRuntime
metadata:
  name: demo1
spec:
  replicas: 1
  tieredstore:
    levels:
      - mediumtype: SSD
        path: /dev/shm
        quota: 20Gi
        high: "0.95"
        low: "0.7"