apiVersion: data.fluid.io/v1alpha1
kind: DataTable
metadata:
  name: partcustomer
spec:
  intelligentCache: false
  url: 210.28.132.15:10000
  schemas:
    - schemaName: ssb
      tables:
        - tableName: ssbpartcustomer
          partitionColumn:
           -  c_comment: AUTOMOBILE
    - schemaName: tpcds
      tables:
        - tableName: store
        - tableName: store_sales

